# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-10 17:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('Id_Registro', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('Id_Sala', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=50, unique=True)),
                ('Localizacion', models.CharField(max_length=30)),
                ('Activo', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('Id_Usuario', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=30)),
                ('Apellidos', models.CharField(max_length=30)),
                ('Clave', models.CharField(max_length=30, unique=True)),
                ('Activo', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='registro',
            name='Sala_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProyectoNFC.Sala'),
        ),
        migrations.AddField(
            model_name='registro',
            name='Usuario_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProyectoNFC.Usuario'),
        ),
    ]
