# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-11 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoNFC', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='Fecha_In',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='registro',
            name='Fecha_Out',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='sala',
            name='Aforo',
            field=models.IntegerField(null=True),
        ),
    ]
