# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-11 20:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoNFC', '0002_auto_20170611_1806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sala',
            name='Aforo',
        ),
        migrations.AlterField(
            model_name='registro',
            name='Fecha_In',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='registro',
            name='Fecha_Out',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='registro',
            name='Sala_Id',
            field=models.ForeignKey(db_column='Nombre_Sala', on_delete=django.db.models.deletion.DO_NOTHING, to='ProyectoNFC.Sala'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='Usuario_Id',
            field=models.ForeignKey(db_column='Nombre_Usuario', on_delete=django.db.models.deletion.DO_NOTHING, to='ProyectoNFC.Usuario'),
        ),
        migrations.AlterField(
            model_name='sala',
            name='Nombre',
            field=models.CharField(db_column='Nombre_Sala', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Nombre',
            field=models.CharField(db_column='Nombre_Usuario', max_length=30),
        ),
    ]
