# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 10:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoNFC', '0004_auto_20170612_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='Sala_Id',
            field=models.ForeignKey(db_column='Nombre_Sala', on_delete=django.db.models.deletion.CASCADE, to='ProyectoNFC.Sala'),
        ),
    ]
