# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 17:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoNFC', '0007_auto_20170612_1250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registro',
            old_name='Sala_Id',
            new_name='Sala',
        ),
        migrations.RenameField(
            model_name='registro',
            old_name='Usuario_Id',
            new_name='Usuario',
        ),
    ]
