# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoNFC', '0008_auto_20170614_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sala',
            name='Nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Nombre',
            field=models.CharField(max_length=30),
        ),
    ]
