# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoNFC', '0012_auto_20170617_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='Dni',
            field=models.CharField(default=52288546, max_length=9, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Clave',
            field=models.CharField(max_length=30),
        ),
    ]
