# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 14:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoNFC', '0014_auto_20170620_1212'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('Id_Permiso', models.AutoField(primary_key=True, serialize=False)),
                ('Permiso', models.BooleanField(default=False)),
                ('Sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProyectoNFC.Sala')),
            ],
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='Clave',
        ),
        migrations.AddField(
            model_name='permiso',
            name='Usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProyectoNFC.Usuario'),
        ),
    ]
