# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoNFC', '0015_auto_20170627_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='Dependencia',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='sala',
            name='Plano',
            field=models.ImageField(default=1, upload_to='photos/'),
            preserve_default=False,
        ),
    ]
