# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoNFC', '0017_auto_20170704_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='Fecha_In',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
