# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-09 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoNFC', '0019_auto_20170709_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sala',
            name='Hash',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
