# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoNFC', '0023_auto_20170712_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='Terminado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='registro',
            name='Fecha_Out',
            field=models.DateTimeField(null=True),
        ),
    ]
